### ISSUE TITLE
[Mac] compile failed with pthread

### ISSUE THREAD

**Issue by woc2006** [unicorn-engine/unicorn#1075]
./make.sh
cd qemu && \
	./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_ARM64 -fPIC -fvisibility=hidden -m32 -arch i386 -m64 -arch x86_64" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, aarch64-softmmu,"

ERROR: pthread check failed
       Make sure to have the pthread libs and headers installed.

make: *** [qemu/config-host.h-timestamp] Error 1

**Comment by woc2006** [comment]
I found the error message in ./qemu/configure line 940, it test pthread with
```
#include <pthread.h>
static void *f(void *p) { return NULL; }
int main(void) {
  pthread_t thread;
  pthread_create(&thread, 0, f, 0);
  return 0;
}
```
this code works in XCode.

**Comment by woc2006** [comment]
I solved the issue.
macOS SDK 10.14 only has x86_64  system libraries.
Remove i386 from Makefile line 117 and 118
![image](https://user-images.githubusercontent.com/1716430/54130756-eebb5080-444b-11e9-8e84-c33dfc570567.png)

**Comment by aquynh** [comment]
how did you compile? 

if you just do `./make.sh`, you should be fine with the latest Github code

**Comment by woc2006** [comment]
> how did you compile?
> 
> if you just do `./make.sh`, you should be fine with the latest Github code

I compile with Unicorn 1.0.1 release, macOS 10.14, XCode 10.1

**Comment by aquynh** [comment]
The latest Github code already fixed this issue

**Comment by SergeyKaAndroid** [comment]
Can we update python3 pip package please?

**Comment by Waterman178** [comment]
thanks

**Comment by Rudybega** [comment]
Ran into this issue today when trying to build Angr on OSX (which has Unicorn as a dependency).  I think the python3 pip package still doesn't have this fix applied.

For those trying to install Angr it can be fixed by:

1. cloning the latest master branch of unicorn from Github
2. running ./make.sh in that branch
3. running sudo ./make.sh install
4. setting up a python3 virtual environment for angr
5. activating that environment
6. Installing unicorn to the angr environment by cding into the bindings/python directory inside unicorn's folder and running: python setup.py install
7. running the following command (note that --python needs to point to a python2 installation): UNICORN_QEMU_FLAGS="--python='whereis python'" pip install angr

Hope this helps anyone running into the same issue.

**Comment by aquynh** [comment]
@rhelmot i suppose the latest Pypi package already fixed all the MacOS issues?

**Comment by saagarjha** [comment]
Not @rhelmot, but I just ran through an angr install on macOS and I think there's a couple of issues. I managed to successfully install unicorn 1.0.2rc1 (`pip3 install unicorn --pre`), but:

* For whatever reason, it would try to pick up the Mono `msbuild` I had and fail miserably? I fixed this by cutting Microsoft out of `$PATH` when installing.
* It would create libunicorn.1.dylib and libunicorn.dylib pointing to it but end up only copying the former, except I think it would do so by resolving through the latter because the resulting product would be named libunicorn.dylib.

On angr's side, I got it to install successfully too but none of the native libraries worked. Mostly because:

* It would link against `-lunicorn` and this would pull in libunicorn.dylib, except that it would insert a versioned load command for libunicorn.1.dylib. (Normally, you'd have both and this would work out.)
* The angr_native.dylib binary (it would be nice if it had a "lib" prefix) and its load commands had no rpaths set, which rendered it impossible to find and load any of the native libraries anyways.

The Makefiles for both projects probably need a couple of tweaks to resolve these.

**Comment by aquynh** [comment]
Pull req, please.

**Comment by saagarjha** [comment]
I have chosen to have angr's dependencies vend themselves as "relocatable" by prefixing their install name with `@rpath`, and then modified angr so that it knows about it. @aquynh the patch you care about is at #1195; @rhelmot you might be interested in https://github.com/angr/pyvex/pull/201 and https://github.com/angr/angr/pull/1932.

**Comment by rhelmot** [comment]
The latest pypi package has absolutely not fixed the macos issues; the rc1 release on pypi is conveniently placed right in between the commit which adds msbuild support and the commit which restricts it to windows only.

**Comment by stock1218** [comment]
@rhelmot I managed to get a working version on macOS via `brew install unicorn`
