### ISSUE TITLE
IP register is wrong in x86 16-bits mode

### ISSUE THREAD

**Issue by macmade** [unicorn-engine/unicorn#1114]
Assuming the following assembly code:

    0x0000: push 0x50
    0x0002: push 0x00
    0x0004: retf
    ...
    0x0500: jmp short 0x00

At `0x0500`, `CS` should be `0x50` and `IP` should be `0x00`.

With unicorn, `CS` is `0x50` but `IP` is `0x500`.  
So it looks like the value of `IP` is always the currently executing address, already computed with regard to `CS`.

I'm not sure where this translation occurs.

Manually setting `CS` to `0x50` and `IP` to `0x00` using `uc_reg_write` is fine.  
Immediately reading `IP` gives `0x00`, but as soon as the emulation continues, while the correct location is executed, `IP` is reset to `0x500`.

As an example:

    #include <stdio.h>
    #include <stdint.h>
    #include <unistd.h>
    #include <unicorn/unicorn.h>

    static void onCode( uc_engine * uc, uint64_t address, uint32_t size, void * data );
    static void onCode( uc_engine * uc, uint64_t address, uint32_t size, void * data )
    {
        int16_t cs = 0;
        int16_t ip = 0;
        uint8_t buf[ 1024 ];
        
        ( void )data;
        
        uc_reg_read( uc, UC_X86_REG_CS, &cs );
        uc_reg_read( uc, UC_X86_REG_IP, &ip );
        uc_mem_read( uc, address, buf, size );
        
        printf( "CS:          0x%04hX\n", cs );
        printf( "IP:          0x%04hX\n", ip );
        printf( "Address:     0x%016llX\n", address );
        printf( "Instruction:" );
        
        for( size_t i = 0; i < size; i++ )
        {
            printf( " %02X", buf[ i ] );
        }
        
        printf( "\n\n" );
        sleep( 1 );
    }

    int main( void )
    {
        uc_engine * uc;
        uc_hook     h;
        
        uc_open( UC_ARCH_X86, UC_MODE_16, &uc );
        uc_mem_map( uc, 0, 1024 * 1024, UC_PROT_ALL );
        uc_hook_add( uc, &h, UC_HOOK_CODE, ( void * )onCode, NULL, 0, UINT64_MAX );
        
        uint8_t c000[] =
        {
            0x6A, 0x50, // push 0x50
            0x6A, 0x00, // push 0x00
            0xCB        // retf
        };
        uint8_t c500[] =
        {
            0xEB, 0xFE // jmp short 0x00
        };
        
        uc_mem_write( uc, 0,     c000, sizeof( c000 ) );
        uc_mem_write( uc, 0x500, c500, sizeof( c500 ) );
        
        uc_emu_start( uc, 0, UINT64_MAX, 0, 0 );
        
        return 0;
    }

**Comment by aquynh** [comment]
i just pushed a fix for #1115, wondering if that affects this issue? can you pull the latest code, and try again?

**Comment by aquynh** [comment]
i mean test this and also other issues.

**Comment by macmade** [comment]
Sure, I’ll test that asap, thanks

**Comment by macmade** [comment]
Unfortunately, issues are still present with the latest changes.
