### ISSUE TITLE
X86_16: wrong starting address after restart

### ISSUE THREAD

**Issue by mf85** [unicorn-engine/unicorn#968]
When the emulation is stopped(uc_emu_stop) and then started(uc_emu_start) using address obtained from ip/eip the emulation starts at wrong address.
Precondition: cs register has to be set manually(which is a must if the program starts at address > 64KB)

`uc_reg_write(uc, UC_X86_REG_CS, &cs);`
`uc_emu_start(uc, begin, -1, 0, 0);`
`// callback stops the emulation`
`uc_reg_read(uc, UC_X86_REG_IP, &begin);`
`uc_emu_start(uc, begin, -1, 0, 0);`

This is caused by the code `*pc = *cs_base + env->eip;`  in function `cpu_get_tb_cpu_state` in
qemu/target-i386/cpu.h
Problem is that for some reason eip contains the whole linear address which already contains the cs_base. Adding the cs_base again makes the address invalid.

This can be easily fixed by subtracting cs_base from eip before restart, but I still consider it a bug.

Example code.
[main.zip](https://github.com/unicorn-engine/unicorn/files/2069760/main.zip)

**Comment by aquynh** [comment]
fixed in https://github.com/unicorn-engine/unicorn/commit/91033dd0f039185635df8b3209d81048fd5fb688, please confirm.

**Comment by mf85** [comment]
Hi, this does not work. Actually it makes it even worse, cos the program wont even start at the right address.
You can try the example code I originally attached.

In my opinion, instead of patching a specific issue like this, you should focus on solving source of the problems and that is the inconsistent content of eip in 16 bit mode.
Sometimes the `eip = ip` and some other time `eip = cs*4 + ip`.
I am writing a 16bit emulator and I have encounterd multiple bugs all dealing with this.

**Comment by aquynh** [comment]
reverted that commit now.

a question: why do you access EIP in 16bit code, but not IP?

**Comment by mf85** [comment]
Answer: 
When something does not work and I do not know why, I just try couple different options.
In this case it does not matter, the result it still the same.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by mf85** [comment]
It seems to work, hope there are no side effects.
gj
